# Supabase configuration file
[api]
enabled = true
port = 54321

[db]
enabled = true
port = 54322

[functions]
enabled = true
verify_jwt = false

[edge_runtime]
enabled = true

[cron]
enabled = true

[hooks]
enabled = true